lowRISC/lowrisc-toolchains

README.md, azure-pipelines.yml, build-gcc-ibex.sh, build-gcc-multilib.sh, install-crosstool-ng.sh, lowrisc-toolchain-gcc-rv32imc.config
crosstool-ng is significantly cleaner than the SiFive-provided toolchain
build script.
=> Ibex: Use crosstool-ng to build toolchain

build-gcc-ibex.sh
We have a broken symlink in the tar file. This should fix that by ensuring that `riscv` is an entire path component, at the start of the string, not at a random part of the path.
=> Attempt to fix symlink

build-gcc-ibex.sh
This adds a JSON toolchain description to the Ibex build.
This is needed for the migration to using the toolchains from #4. The JSON format matches the JSON keys and value formats in that pull request.
The intent is that this JSON replaces the text-based buildinfo, so that the get toolchain util in opentitan can parse a more reasonable format.
=> Add JSON Description to Ibex Toolchain

README.md, lowrisc-toolchain-gcc-rv32imc.config, patches/gcc/git-49f75e00/001-bitmanip.patch
- Changes the binutils git remote to point to GitHub, to allow shallow
clones using a specific commit;
- Adds the GCC bitmanip patches, using the same approach previously used
for binutils;
- Updates and tweaks the `README.md`.
=> Finish adding bitmanip patches

lowrisc-toolchain-gcc-rv32imc.config
We now build the toolchain (including libraries) with only rv32imc (as
before we landed the bitmanip patches). With the B extension compiler
and binutils patches landed, the compiler should still be able to
compile for cores with the +B extension, but this change prevents issues
if your core does not implement the B extension, which is the case for
mainline Ibex today.
Code with the B extension enabled should be linkable with libraries with
the B extension disabled.
---
Closes #12 (if it builds).
=> [Ibex] Disable Bitmanip in Libraries

lowrisc-toolchain-gcc-rv32imc.config
With the previous config, we were accidentally building a GCC 10.0.0
experimental version of GCC. In order to make the toolchain migration go
as smoothly as possible for OpenTitan, I'm reverting to building the
same version as we were building before (9.2.0).
I will follow-up with a patch that includes the config for RV32IMC+B, as
this does require a git version of GCC because we apply patches on top
of it.
Signed-off-by: Sam Elliott <selliott@lowrisc.org>
=> Downgrade RV32IMC GCC to 9.2.0

build-clang-with-args.sh, build-gcc-with-args.sh
This helps OpenTitan's `get-toolchain.py` tool differentiate between the GCC
and GCC+Clang toolchains, even if they have the same version.
=> Add kind field to buildinfo.json

_build-deps.yml, _upload-artifacts.yml, azure-pipelines.yml, build-clang-with-args.sh, build-gcc-with-args.sh
---
The idea here is to use a separate, short, bash script to set `ReleaseTag`, and then for all tasks to use the same `ReleaseTag` value, rather than the GCC build setting it and the clang build potentially using a different tag.
We also do a few things that support this:
- If this is a tag build, we definitely use the tag.
- If it's a branch build, we use the `<tag>-<n>-<sha>` format.
- We only upload artefacts that have a name that matches the ReleaseTag.
=> Set ReleaseTag More Accurately

_upload-artifacts.yml, build-clang-with-args.sh, build-gcc-with-args.sh, check-tarball-symlinks.sh, create-prefixed-archive.sh
This is now the same one that we use for gcc. The reason for this is
because we're tar-ing up some files that GCC produces too. The transform
was wrong for GCC in the past, and this ports that fix onto current
master.
---
Issue noted by @imphil in https://github.com/lowRISC/opentitan/pull/2524#issuecomment-645360269
=> [clang] Correct tar filename Transform

lowrisc-toolchain-gcc-rv32imc.config, lowrisc-toolchain-gcc-rv32imcb.config
---
We do this for clang, it makes sense to do it for the binutils/gcc build too.
=> [gnu] Provide Toolchain Bug Report URL (Email)

build-gcc-with-args.sh
In some azure logs I was seeing messages that said `CT_PREFIX_DIR` set twice, and was confused, but looking at the .config files, some do contain `CT_PREFIX_DIR=`. This removes them and means we can override them with `$toolchain_dest` correctly.
=> [gnu] Override CT_PREFIX_DIR Correctly

check-tarball-symlinks.sh
This is a follow-up regression test that covers the issue uncovered in #25.
=> [checks] Add Check for buildinfo

lowrisc-toolchain-gcc-rv64imac.config
Attempting to address #42.
An alternative I've seen is to add `-mcmodel=medany` to `CFLAGS_FOR_TARGET`, but I can't immediately see how to do that.
=> Fix code model for Muntjac libraries

azure-pipelines.yml, build-clang-with-args.sh, sw-versions.sh
Updates LLVM to use the `ot-hardening` branch from <https://github.com/lowRISC/llvm-project.git>.
Since the non-bitmanip builds don't seem to be needed anymore (and since we can keep using old releases), those have been removed in this release.
=> Update toolchain with hardening patches

sw-versions.sh
This new LLVM commit includes:
- Support for the `.option noguards`.
- A fix for the jump guards hardening.
=> Update LLVM hardening patches version

.github/workflows/toolchain_build.yml, _build-deps.yml, install-crosstool-ng.sh, prepare-ubuntu-20.04.sh, release_tag.sh
This PR adds a GitHub Actions workflow that should be equivalent to the Azure pipeline.
This does not remove the existing Azure pipeline.
This workflow:
* Builds GCC and Clang for RV32IMCB and RV64IMAC (plus extras like binutils).
* Checks that no binaries are dynamically linked to non-system libraries.
* Runs for the master branch, PRs to the master branch, and pushed tags.
* Pushed tags trigger a release which is automatically created and given the tarballs.
I've tested this works on my fork of this repo:
1. [Release run](https://github.com/jwnrt/lowrisc-toolchains/actions/runs/7196753719) and [the release](https://github.com/jwnrt/lowrisc-toolchains/releases/tag/20231213-1).
2. [Master branch run](https://github.com/jwnrt/lowrisc-toolchains/actions/runs/7196677130).
If we choose to …
=> Add GitHub Actions workflow for building and releasing toolchains

.github/workflows/toolchain_build.yml, prepare-centos-7.sh
This test adds the `gh` GitHub CLI tool to the CentOS 7 environment. This is used for creating releases.
I've extracted the package list to a `prepare-centos-7.sh` script to match how the other ones worked.
=> Install gh CLI on centos 7

lowrisc-toolchain-gcc-rv32imc.config, lowrisc-toolchain-gcc-rv32imcb.config
@engdoreis and I discovered that newlib generates syscalls when stdio functions are used. This is not desirable and it's preferable to just have linker error instead for baremetal targets.
=> Disable newlib syscalls for baremetal target

.github/workflows/toolchain_build.yml
These old versions will be deprecated soon. We couldn't update them before because they required Node.js 20 which we now have from updating to AlmaLinux 8.
=> Bump GitHub Actions versions

.github/workflows/toolchain_build.yml, build-clang-with-args.sh, build-gcc-with-args.sh
The opentitan project uses the prebuilt toolchain on X86 to reduce build time. With the changes to the `toolchain_build.yml` workflow we also build the artifacts for aarch64.
Resolves #83
=> Build toolchains for aarch64

sw-versions.sh
Update LLVM version with single-byte coverage mode from PR https://github.com/lowRISC/llvm-project/pull/4
These changes are specific to coverage builds and remain compatible with the current compiler.
=> Update LLVM version with single-byte coverage mode

sw-versions.sh
Update LLVM version with single-byte coverage fix from PR:
* https://github.com/lowRISC/llvm-project/pull/5
These changes are specific to coverage builds and remain compatible with the current compiler.
=> Update LLVM version with fix for elided branches coverage
